site_name: Belajar Pajak
site_url: https://diasbaskara.id/

theme:
  name: material
  language: id
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - header.autohide
    - toc.follow

  font:
    text: Work Sans

  palette:
    scheme: slate
    primary: black
    accent: grey

nav:
  - Beranda: index.md
  - Istilah:
    - istilah/index.md 
    - NPWP: istilah/npwp.md
  - Pekerjaan:
    - pekerjaan/index.md
    - Arsitek: pekerjaan/arsitek.md
    - Artis: pekerjaan/artis.md
    - Desainer: pekerjaan/desainer.md
    - Dokter: pekerjaan/dokter.md
    - Karyawan BUMN: pekerjaan/karyawan-bumn.md
    - Kepala Daerah: pekerjaan/kepala-daerah.md
    - Konsultan: pekerjaan/konsultan.md