site_name: Belajar Pajak
site_url: https://diasbaskara.id/
nav:
    - ...
    - tags.md
    - FAQs: FAQs
    - tentang.md
theme:
  name: material
  custom_dir: overrides
  language: id
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.instant
    - header.autohide
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tooltips
    - announce.dismiss
  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3

  font:
    text: Work Sans

  palette:
    scheme: slate
    primary: black
    accent: grey

plugins:
  - search
  - awesome-pages
  - table-reader
  - macros
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
  - tags:
      tags_file: tags.md
  # - encryptcontent:
  #   global_password: 'belajar'

extra:
  social:
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/diasbaskara
      name: diasbaskara on Instagram
    - icon: fontawesome/brands/github 
      link: https://github.com/diasbaskara
      name: diasbaskara on GitHub
  tags:
    HTML5: html
    JavaScript: js
    CSS: css

copyright: Copyright &copy; 2024 Dias Baskara

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  # - javascripts/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css