site_name: My Docs
site_url: https://diasbaskara.id/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - header.autohide
nav:
  - Home: index.md
  - About: about.md