site_name: Belajar Pajak
site_url: https://diasbaskara.id/

theme:
  name: material
  language: id
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - header.autohide
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tooltips

  font:
    text: Work Sans

  palette:
    scheme: slate
    primary: black
    accent: grey

plugins:
  - search
  - table-reader
  - external-markdown
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true

extra:
  social:
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/diasbaskara
      name: diasbaskara on Instagram
    - icon: fontawesome/brands/github 
      link: https://github.com/diasbaskara
      name: diasbaskara on GitHub

copyright: Copyright &copy; 2024 Dias Baskara

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.snippets

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js